# Generated by Django 5.2.5 on 2025-12-17 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_projectteam_invited_at_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('probability', models.PositiveSmallIntegerField()),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loss_percentage', models.PositiveSmallIntegerField()),
                ('calculated_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk_decision', models.CharField(choices=[('Avoid', 'Avoid'), ('Mitigate', 'Mitigate'), ('Transfer', 'Transfer'), ('Accept', 'Accept')], max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('InProgress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('mitigation_status', models.CharField(choices=[('NotStarted', 'Not Started'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='NotStarted', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
        ),
    ]
