# Generated by Django 5.2.5 on 2025-12-16 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_projectteam_invited_at_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('probability', models.PositiveSmallIntegerField()),
                ('risk_exposure', models.PositiveSmallIntegerField(editable=False)),
                ('risk_level', models.CharField(editable=False, max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loss_percentage', models.PositiveSmallIntegerField(editable=False)),
                ('calculated_loss', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('risk_decision', models.CharField(choices=[('accept', 'Accept'), ('mitigate', 'Mitigate'), ('transfer', 'Transfer'), ('avoid', 'Avoid')], max_length=20)),
                ('mitigation_suggestion', models.TextField(blank=True)),
                ('assigned_to', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
        ),
    ]
