# Generated by Django 5.2.5 on 2025-12-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='mitigation_suggestion',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_exposure',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_id',
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='calculated_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='loss_percentage',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_decision',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
