# Generated by Django 5.2.5 on 2025-12-18 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='calculated_loss',
        ),
        migrations.AddField(
            model_name='risk',
            name='likelihood',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='loss_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='mitigation_status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='NotStarted', max_length=20),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
