# Generated by Django 5.2.5 on 2025-12-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_remove_risk_calculated_loss_risk_likelihood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='loss_percentage',
        ),
    ]
