# Generated by Django 5.2.5 on 2026-01-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_remove_risk_loss_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
