# Generated by Django 5.2.5 on 2026-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_risk_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
