# Generated by Django 5.2.5 on 2026-02-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_risk_approved_at_risk_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='tm_mitigation_suggestion',
            field=models.TextField(blank=True, help_text='Mitigation suggestion proposed by Team Member'),
        ),
        migrations.AddField(
            model_name='risk',
            name='tm_suggestion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
