# Generated by Django 5.2.5 on 2026-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
