# Generated by Django 5.2.5 on 2025-09-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.CharField(max_length=100),
        ),
    ]
