# Generated by Django 5.2.5 on 2025-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectteam_invited_at_invite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectteam',
            options={},
        ),
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('TM', 'Team Member')], default='TM', max_length=10),
        ),
    ]
