# Generated by Django 5.2.5 on 2026-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_verified_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('TM', 'Team Member'), ('AD', 'Admin')], default='TM', max_length=2),
        ),
    ]
